# -*- coding: utf-8 -*-
"""HW4_1660707223.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0ILUU3pAE377PdEIPkoxPOyt_4XpTBW
"""

print("="*43)
print("%-11s %s %11s"%("|", "*** Order Total ***", "|"))
print("-"*43)
order = int(input("Enter Order summary : "))
print("-"*43)
print("%-1s %s %28s"%("|", "Destination:", "|"))
print("%-4s %s %s"%("|", "(BK) The Bangkok Metropolitan Region", "|"))
print("%-4s %s %4s"%("|", "(TH) For areas in other provinces", "|"))
print("-"*43)
des = input("Enter destination       : " ).upper()
if des == "BK" or des == "TH" :
  weight = int(input("Enter total weight(KG.) : "))
  print("-"*43)
  print("%-4s %s %4s %5s %6s %5s %6s"%("|","Weight:","|","BK","|","TH","|"))
  print("-"*43)
  print("%-6s %s %6s %6s %5s %6s %5s"%("|","1-5","|","80","|","140","|"))
  print("%-6s %s %5s %6s %5s %6s %5s"%("|","6-10","|","150","|","200","|"))
  print("%-6s %s %6s %6s %5s %6s %5s"%("|","10+","|","200","|","250","|"))
  print("-"*43)
  if des == "BK" : #BKK area
    if weight <= 5 :
      shipping = 80
    elif weight <= 10 :
      shipping = 150
    else :
      shipping = 200
  else : #TH area
    if weight <= 5 :
      shipping = 140
    elif weight <= 10 :
      shipping = 200
    else :
      shipping = 250
  print("Order summary : %.2f"%(order))
  print("Shipping %4s : %s %.2f"%("","",shipping))
  if order > 3000:
    if  order < 5001:
      disc = 60
    elif order > 5000:
      disc = 120
    print("Discount %4s : -%.2f"%("",disc))
    total = order + shipping - disc
    print("="*24)
    print("Order Total %1s : %.2f"%("",total))
    print("="*24)
  else :
    disc = 0
    print("Discount %4s : %2s %.2f"%("","",disc))
    total = order + shipping - disc
    print("="*24)
    print("Order Total %1s : %.2f"%("",total))
    print("="*24)
else :
  print("Invalid destination code! Try again.")